let prefList = [
  { number: 1, name: "北海道" },
  { number: 2, name: "青森県" },
  { number: 3, name: "岩手県" },
  { number: 4, name: "宮城県" },
  { number: 5, name: "秋田県" },
  { number: 6, name: "山形県" },
  { number: 7, name: "福島県" },
  { number: 8, name: "茨城県" },
  { number: 9, name: "栃木県" },
  { number: 10, name: "群馬県" },
  { number: 11, name: "埼玉県" },
  { number: 12, name: "千葉県" },
  { number: 13, name: "東京都" },
  { number: 14, name: "神奈川県" },
  { number: 15, name: "新潟県" },
  { number: 16, name: "富山県" },
  { number: 17, name: "石川県" },
  { number: 18, name: "福井県" },
  { number: 19, name: "山梨県" },
  { number: 20, name: "長野県" },
  { number: 21, name: "岐阜県" },
  { number: 22, name: "静岡県" },
  { number: 23, name: "愛知県" },
  { number: 24, name: "三重県" },
  { number: 25, name: "滋賀県" },
  { number: 26, name: "京都府" },
  { number: 27, name: "大阪府" },
  { number: 28, name: "兵庫県" },
  { number: 29, name: "奈良県" },
  { number: 30, name: "和歌山県" },
  { number: 31, name: "鳥取県" },
  { number: 32, name: "島根県" },
  { number: 33, name: "岡山県" },
  { number: 34, name: "広島県" },
  { number: 35, name: "山口県" },
  { number: 36, name: "徳島県" },
  { number: 37, name: "香川県" },
  { number: 38, name: "愛媛県" },
  { number: 39, name: "高知県" },
  { number: 40, name: "福岡県" },
  { number: 41, name: "佐賀県" },
  { number: 42, name: "長崎県" },
  { number: 43, name: "熊本県" },
  { number: 44, name: "大分県" },
  { number: 45, name: "宮崎県" },
  { number: 46, name: "鹿児島県" },
  { number: 47, name: "沖縄県" },
];

export default {
  prefList,
};
